migueldeicaza/SwiftGodot

Generator/Generator/ClassGen.swift

https://github.com/migueldeicaza/SwiftGodot/issues/33
I created a `Node2D` subclass and overrode `_ready()` and `_input(event:)` and in both cases add a child node of a certain name.
Before making the change this happens on game launch & player input...
After making the change this is the result

only guard unwrap args if there are arguments

---

Sources/SwiftGodot/Extensions/GD+Utils.swift

This PR adds new `load`, `print`, and `pushError`/`pushWarning` methods to the global scope GD class.
The load function works similarly to that of GD.Load in the C# variant and is a means of being consistent with the GDScript preload function.
Three new print methods are also available, which function similarly to Swift's traditional print function. These methods also handle converting the items accordingly to ensure they get represented properly, as well as converting the resulting string to the Variant type that the normal GD.print methods require.

Add load and print family of utilities in GD

---

Sources/SwiftGodot/Core/ObjectCollection.swift

I am running into a crash for this scenario..
I have a class I created in `SimpleExtension` named `UIGround` that is a subclass of `Node2D` and registered the object to use in Godot.
The makeup of this scene in Godot is:
```
- Ground (UIGround)
- Sprite2D
- Area2D
- CollisionShape2D
```
I have another class `PlayerActions` that has a `Area2D` which I use to call `Area2D.getOverlappingAreas()` which returns the `Godot.Area2D` which it is not able to lookup in `liveFrameworkObjects` or `liveSubtypedObjects` because the `nativeHandler` doesn't exist for that object.
By using `lookupObject<T>(nativeHandler:) -> T` it first does the `objectFromHandle(nativeHandle:) --> Wrapped?` check and if it doesn't exist there does the `gi` call and successfully returns the typed object.
Maybe there is a …

Fix ObjectCollection Subscript Crash

---

README.md

~~So it can be generated with `swift package generate-xcodeproj`~~
Edit: Nevermind that, it's deprecated. 
Still fixes issues with semicolons and matching closing tags.

Fixing the SwiftPM example

---

Sources/SwiftGodot/Extensions/ClassInfo+ConvenienceProperties.swift
scripts/make-swiftgodot-framework
scripts/release

This PR adds some new helper methods I've written to improve the general process of registering certain types of data fields:
- `registerCheckbox` registers a toggleable boolean value, rendered as a checkbox in the editor.
- `registerEnum` registers an enum that can be expressed as an integer. The signature calls for conformance to `Nameable` which would allow the names to show up correctly in the editor.
- `registerInt` registers a range picker for an integer value.
- `registerFilePicker` registers a file picker to pick from a series of files. For macOS 10.15, this accepts a string array of the file extensions. For macOS 11.0+, this accepts an array of uniform type idenfitiers (UTType). In turn, this also includes some UTType instance for various Godot-specific files such as `tscn` and …

Add convenience registration methods, fix build scripts

---

Package.swift

CodeGeneratorPlugin's dependency should be enough, There's no need for the core target to depend on Generator.

Clean up unnecessary dependency

---

Sources/SwiftGodot/Core/ClassServices.swift
Sources/SwiftGodot/Core/ObjectCollection.swift
Sources/SwiftGodot/Core/VariantCollection.swift
Sources/SwiftGodot/Variant.swift

GDExtensionVariantType.RawValue is Int32 when building on Windows. Using RawValue abstraction instead of concrete type should help to avoid type mismatch.

Use GDExtensionVariantType.RawValue abstraction

---

Sources/SwiftGodot/Extensions/ClassInfo+ConvenienceProperties.swift

Since the framework is not available for platforms other than macOS.

Add availability checks for UniformTypeIdentifiers

---

Sources/SwiftGodot/Export.swift

Don't know why, but C enums on Windows implicitly get signed integer as the underlying type, which results in type mismatch for method_flags assignment (which is explicitly declared as uint32_t). This was also the cause for type mismatch at #123. Doesn't happen when building on Ubuntu.

Fix method flags type mismatch on Windows

---

README.md
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/Package-starter-4.swift

The tutorial now includes the step for adding SwiftGodotMacros to Package.swift.
The README now also demonstrates the initSwiftExtension macro.

Update docs, tutorial

---

Sources/SwiftGodotMacros/MacroDefs.swift

```swift
#initSwiftExtension(cdecl: "swift_entry_point", types: [
Jumper.self,
Circle.self,
MainScene.self,
HUD.self,
BaseScreen.self,
Screens.self,
AboutScreen.self,
])
```
This code was failing with:
>CircleJumpDriver.swift:19:5: error: cannot convert value of type 'BaseScreen.Type' to expected element type 'Array<AboutScreen.Type>.ArrayLiteralElement' (aka 'AboutScreen.Type')
BaseScreen.self,
This is because the generic on the `initSwiftExtension` definition was set up to expect an array of identically typed classes.
This PR changes the type to just be:`[Wrapped.Type]` which allows any types that conform to `Wrapped`, as opposed to a being an array of a single specific type that conforms.

Fix issue where `initSwiftExtension` types were expected to be homogenous

---

Sources/SwiftGodotMacroLibrary/SceneTreeMacro.swift
Tests/SwiftGodotMacrosTests/SceneTreeMacroTests.swift

Since I know that I'm only going to reference these properties after they are available in `_ready()`, I prefer to implicitly unwrap the optional. At the moment a diagnostic warning prevents me from doing this. This PR loosens the requirement a bit so that we can use `!` as well as `?`. It will still emit a diagnostic if the type is missing both.
```swift
class MainScene: Node {
@SceneTree(path: "StartPosition") var startPosition: Marker2D!
@SceneTree(path: "Camera2D") var camera: Camera2D!
}
```

Permit implictly unwrapped optionals when using @SceneTree

---

Sources/SwiftGodotMacroLibrary/MacroGodot.swift
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift

The macro was expanding to register a func with the literal name "funcName" instead of the contents of the variable `funcName`.
Also adds tests for the Godot, Export and Callable macros.

Fixes issue where Callable macro expansion would not register method correctly

---

Generator/Generator/Printer.swift
Plugins/CodeGeneratorPlugin/plugin.swift

1. `buildCommand` does not work on Windows seemingly because of an SPM bug. I described the whole thing in https://github.com/apple/swift-package-manager/issues/6962. Using `prebuildCommand` instead fixes the issue.
2. After fixing codegen command Windows build fails with `You don't have permission` error. I suggest it's because generator executable doesn't have write permissions to the temporary directory `Foundation` implementation uses for atomic writes, since toggling off `atomically` fixed the issue for me. Not sure what benefit atomic writes can bring in context of code generator, so I disabled it for all platforms.

Fix source generation on Windows

---

Package.swift

To match the existing linking behavior of the base library.

Make SwiftGodotMacros a dynamic library

---

Package.swift

- macOS keeps `dynamic_lookup`
- Windows linking gets past settings-related error mentioned in #146 
- Linux doesn't seem to be affected by this. Got a successful build of macro-based GDExtension without `dynamic_lookup` in both `SwiftGodot` and extension's packages.

Adjust linker settings since dynamic_lookup is macOS-specific

---

.spi.yml

Once merged, this will add a "Documentation" menu item on the [SwiftGodot SPI listing](https://swiftpackageindex.com/migueldeicaza/SwiftGodot).

Added a `.spi.yml` file to tell the Swift Package Index where to find the documentation

---

Generator/Generator/Arguments.swift
Generator/Generator/ClassGen.swift
Generator/Generator/Enums.swift
Generator/Generator/StringOperations.swift
Generator/Generator/TypeHelpers.swift
Package.swift
Sources/SimpleExtension/Demo.swift
Sources/SwiftGodot/Core/ClassServices.swift
Sources/SwiftGodot/Core/SignalSupport.swift
Sources/SwiftGodot/Extensions/ClassInfo+ConvenienceProperties.swift
Sources/SwiftGodot/SwiftGodot.docc/CustomTypes.md
Sources/SwiftGodot/SwiftGodot.docc/Signals.md
Sources/SwiftGodotMacroLibrary/MacroGodot.swift
TestEditor/project.godot
Testbed/default_env.tres
Testbed/main.tscn
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift

Fixes issue: https://github.com/migueldeicaza/SwiftGodot/issues/144
The generator will now find the common prefix among all case names instead of relying on the enum definition name.
You can see the changes to the generated API in this gist: https://gist.github.com/PadraigK/af78939c3e597635d6db5dc98e7b6c64

Change enum prefix detection strategy

---

Makefile
Package.swift
README.md
Sources/SimpleExtension/Demo.swift
Sources/SwiftGodot/MacroDefs.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/MainLevel-multiscript-3.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/MainLevel-multiscript-4.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/MainLevel-multiscript-5.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/MainLevel-multiscript-6.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/MainLevel-multiscript-init.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/Package-starter-4.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/SimpleRunnerDriver-multiscript-2.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/SimpleRunnerDriver-starter-2.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/SimpleRunnerDriver-starter-3.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/SwiftGodotKit-Main.swift
Sources/SwiftGodot/SwiftGodot.docc/Tutorials/Writing Multiple Scripts.tutorial
Sources/SwiftGodot/SwiftGodot.docc/Tutorials/Your First Extension.tutorial
Tests/SwiftGodotMacrosTests/InitSwiftExtensionMacroTests.swift

This should avoid all the complications discussed in #148, leaving `SwiftGodot` the only dependency and only import to worry about for the users. And it'll keep the initial composition of `libDriver.dylib`+`libSwiftGodot.dylib` as the build output.
But it'll require additional workarounds for Windows, since macros aren't supported there yet.

Move macro definitions into SwiftGodot target

---

Sources/SwiftGodot/SwiftGodot.docc/SwiftGodot Tutorials.tutorial

Tiny grammar fix that I spotted when reading through your lovely tutorials (hat tip to Dave Verwer for the link from IOSDevWeekly last week)

Update SwiftGodot Tutorials.tutorial - grammar fix

---

Generator/Generator/BuiltinGen.swift
Generator/Generator/main.swift
Sources/SwiftGodot/Extensions/Endable.swift

Should fix #173. This PR should also make `Color` and `Plane` generation work fine out of the box (unless you want `red` instead of the documented `r`, in that case I'll revert it).

Limit struct stored property generation to members with offsets

---

WINDOWS_BUILD.md

A first pass on a document outlining what is needed to build a project on the Windows platform.

Adds documentation for building on Windows

---

Generator/Generator/BuiltinGen.swift
Generator/Generator/ClassGen.swift
Generator/Generator/MethodGen.swift
Sources/SimpleExtension/Demo.swift
Sources/SwiftGodot/Core/ClassServices.swift
Sources/SwiftGodot/Core/ObjectCollection.swift
Sources/SwiftGodot/Core/SignalRegistration.swift
Sources/SwiftGodot/Core/StringExtensions.swift
Sources/SwiftGodot/Core/VariantCollection.swift
Sources/SwiftGodot/MacroDefs.swift
Sources/SwiftGodot/Variant.swift
Sources/SwiftGodotMacroLibrary/MacroCallable.swift
Sources/SwiftGodotMacroLibrary/MacroGodot.swift
Sources/SwiftGodotMacroLibrary/MacroSharedApi.swift
Sources/SwiftGodotMacroLibrary/SignalMacro.swift
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift

Adds a new freestanding macro that can be used inside a `@Godot` class to register a signal with Godot. 
Signal arguments can be defined and their types will be enforced on new `emit(signal:_argument)` methods.
```swift
@Godot 
class Player: Node2D {
#signal("game_started")
#signal("lives_changed", argument: ["new_lives_count": Int.self])
func startGame() {
emit(Player.gameStarted)
emit(Player.livesChanged, 5)
}
}
class Level: Area2D {
func _ready() { 
player.connect(Player.gameStarted, to: self, method: "game_started")
}
@Callable func game_started() { 
GD.print("got game started signal!")
}
}
```
This all works nicely with the Godot editor too — signals are exposed there and can be connected to GDScripts and well use the argument names provided in the `#signal` invocation. 
---
I did …

Adds #signal Macro 

---

Sources/SwiftGodot/MacroDefs.swift
Sources/SwiftGodotMacroLibrary/InitSwiftExtensionMacro.swift
Tests/SwiftGodotMacrosTests/InitSwiftExtensionMacroTests.swift

In the [Your First Extension](https://migueldeicaza.github.io/SwiftGodotDocs/tutorials/swiftgodot/your-first-extension) tutorial, section 1, step 6, the documentation suggests the following line:
```swift
#initSwiftExtension(cdecl: "swift_entry_point", types: [])
```
However, this currently causes an error: `Empty collection literal requires an explicit type`, due to the resulting line in the macro expansion `let types = []`.
As the easiest way to fix this, I simply added `: [Wrapped.Type]` into the macro expansion. But while doing this, I thought it could be a nice addition to give the `types` parameter a default value of `[]`. This way, the above macro with no types can be simplified to:
```swift
#initSwiftExtension(cdecl: "swift_entry_point")
```
This has the effect of allowing `types` …

Fix #initSwiftExtension failing on empty types

---

Sources/SwiftGodot/Core/VariantRepresentable.swift
Sources/SwiftGodot/Variant.swift

Fixes an issue where it was not possible to init Variant with `Nil`

Make `Nil` initializer on Variant public

---

Sources/SimpleExtension/Demo.swift
Sources/SwiftGodot/Core/SignalRegistration.swift
Sources/SwiftGodot/Core/VariantRepresentable.swift
Sources/SwiftGodot/Core/VariantStorable.swift
Sources/SwiftGodot/MacroDefs.swift
Sources/SwiftGodotMacroLibrary/MacroCallable.swift
Sources/SwiftGodotMacroLibrary/MacroGodot.swift
Sources/SwiftGodotMacroLibrary/MacroSharedApi.swift
Sources/SwiftGodotMacroLibrary/SignalMacro.swift
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift

Adds a new freestanding macro that can be used inside a `@Godot` class to register a signal with Godot. 
Signal arguments can be defined and their types will be enforced on new `emit(signal:_argument)` methods.
```swift
@Godot 
class Player: Node2D {
#signal("game_started")
#signal("lives_changed", argument: ["new_lives_count": Int.self])
func startGame() {
emit(Player.gameStarted)
emit(Player.livesChanged, 5)
}
}
class Level: Area2D {
func _ready() { 
player.connect(Player.gameStarted, to: self, method: "game_started")
}
@Callable func game_started() { 
GD.print("got game started signal!")
}
}
```
This all works nicely with the Godot editor too — signals are exposed there and can be connected to GDScripts and well use the argument names provided in the `#signal` invocation. 
---
This PR …

Add Signal Macro

---

README.md

My main goal was to document key video on `why SwiftGodot makes sense`:
https://www.youtube.com/watch?v=tzt36EGKEZo
https://media.ccc.de/v/godotcon2023-57866-swift-godot-fixing-the-multi-million-dollar-mistake
Would this link be better?
The lesson I learned from video was:
`No game stutters caused by GC, unlike C#.`
Maybe there is a better way to word this. Feel free to offer suggestion in case it feels wrong.
I moved Slack to community section because I feel this deserves it's own section.

README: Add Why SwiftGodot and Community sections

---

Generator/Generator/BuiltinGen.swift

Fixes #225. Though I don't think Extension API's way of describing constant values has anything to do with constructors. It looks more like a memory dump. Anyway, this workaround should patch the existing solution.

Add fallback for builtin constants with missing plain constructors

---

Generator/Generator/ClassGen.swift
Sources/SwiftGodot/MacroDefs.swift
Sources/SwiftGodotMacroLibrary/MacroGodot.swift
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift

Fixes https://github.com/migueldeicaza/SwiftGodot/issues/168
This changes the macro to stop generating `init` methods which were making inheritance a challenge. 
Instead the root class calls an overridable class var with a getter that calls a static method that does the one-time initialization. 
This might look a bit round-about at first glance but works around two limitations in Swift: 
1. Class Initializers are not a supported language thing, so we're approximating them here.
2. class properties can only be calculated properties, not blocks as we would like, so we use a computed class property to call the `static` property that actually does the work. This allows us to support inheritance and ensures that the class initializer is called only once per class.

Fixes inheritance when using `@Godot` macro

---

Sources/SwiftGodotMacroLibrary/MacroCallable.swift
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift

I think there's an argument that a Variant shouldn't be used as the type here at all. Instead the underlying an object matching the Variant's underlying GType could be used. We _could_ explicitly require `@Callable` params to conform to `VariantStorable` to discourage operating in Variants in your Swift logic and give an error that points the way. I can make a PR to add that restriction if that would be preferable. 
If we just want to make it work for now, this PR should fix #236

Fixes issue where Variant parameter to `@Callable` function fails to compile

---

.spi.yml

The docs have now been generated for SwiftGodot and can be switched over if you like: https://swiftpackageindex.com/builds/5A228EAD-CFE2-4EB1-AE24-B5F26D0A7FD2
This is just for `main` at the moment until there are future releases with the updated `.spi.yml` file, of course.

Change documentation link to SPI

---

Sources/SwiftGodotMacroLibrary/MacroGodot.swift
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift

Fixes: #244 
Use appropriate access control on `classInitializer` for final classes
Uses `public` for `final class` and `open` otherwise

Fix support for final classes when using the Godot macro

---

Generator/Generator/ClassGen.swift
Generator/Generator/MethodGen.swift
Sources/SwiftGodot/Core/ObjectCollection.swift
Sources/SwiftGodot/Core/Wrapped.swift

Works around the Swift bug identified in https://github.com/migueldeicaza/SwiftGodot/issues/238 by making the initializers on `Wrapped` public.
I also did some tidying while I was in the area:
* The `init(fast: Bool)` initializer wasn't doing anything, so I removed it. 
* There was no need to generate boilerplate initializers on subclasses, so I removed them all.
* `init (name: StringName)` is reworked a bit; now there's just `init` and it checks a class property for the name. This allows us to make `init()` public and required and remove the `internal` init, which is the thing that triggers the Swift bug in the issue above.  I think this is also a bit cleaner too, since for a given concrete class, there should only be one possible value for the `name` parameter.
The changes in generated …

Tidy up initializers

---

Sources/SwiftGodotMacroLibrary/MacroGodot.swift
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift

PR #245 fixed `final class` when there were no method overrides
This PR ensures that `implementedOverrides` also uses the correct access modifier
Without this fix final classes with overrides produce errors in the form of:

Further fix to support for final classes when using the Godot macro

---

Sources/SwiftGodot/Variant.swift

Just a small quality of life improvement. it's a bit swifty too.
Allows for example:
```swift
let someNode = variant.asObject(SomeNode.self)
let someNodes = garray.compactMap { $0.asObject(SomeNode.self) }
```

add param `_ type: T.Type = T.self` to `Variant.asObject` method

---

Generator/Generator/BuiltinGen.swift

to StringName, NodePath and GString
Meaning that in addition to creating these from a string literal:
```
let str : StringName = "value"
let node = Node3D("NodeName")
```
You can now also create them from string literals with interpolations:
```
let value = 1
let str : StringName = "value: \(value)"
let node = Node3D("NodeName \(value)")
```

Add ExpressibleByStringInterpolation conformance

---

Sources/SwiftGodot/Extensions/GD+Utils.swift

This duplicates the `print_debug` command in Godot, which prints a message, but inserts a new line with debug info, such as the file, line, and function
Here is the example gdscript output
```
Hello World
At: res://folder/node.gd:50:_ready()
```
- new line below the print message
- indented 3 spaces (we could add a param for this indentation width)
- includes the folder/file name, relative to the res folder (we will use `#fileID` for this)
- includes line number (use `#line`) for this
- includes function name (use `#function` for this)
Here is the usage:
```swift
import SwiftGodot
@Godot
class ArrayTest: Node {
override func _ready() {
GD.printDebug("Hello World")
}
}
```
Here is the output in the godot console:
```
Hello World
At: BulletHellper/ArrayTest.swift:6 in _ready()
```

adds `GD.printDebug`, which outputs the .swift file name, as well as the function and line of the caller.

---

Sources/SwiftGodotMacroLibrary/MacroGodot.swift

This catches the problem of forgetting to call register(type:) on a class marked with the @Godot macro.

Assert that a class has been registered before use

---

Plugins/CodeGeneratorPlugin/plugin.swift

You're probably not seeing related compilation errors because you have those files cached from 4.1.3 generation.

4.2: Remove classes not present in extension_api.json from the known list

---

Sources/SwiftGodot/Extensions/NodeExtensions.swift
Sources/SwiftGodot/SwiftGodot.docc/Info.plist

Close #289
Use `wrappedKeyPath` instead of `storageKeyPath` as name
Refactor `BindNode` as a macro
1. `_enclosingInstance` is not officially supported.
See https://forums.swift.org/t/question-about-enclosinginstance-function-in-property-wrappers/59206
2. Add support for custom name mapping from Godot name to Swift name

Fix BindNode crash issue

---

Generator/Generator/MethodGen.swift
Sources/SwiftGodot/EntryPoint.swift

Perhaps it would make sense to use a single implementation of `withArgPointers` instead of generating specific ones for each method? It can also be reused to rewrite calls of built-in structs in a similar manner.

Simplify method calls generation

---

Sources/SwiftGodotMacroLibrary/MacroExport.swift
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift

Fixes #207 again :p
the value in `\(varName)` is always coming in as nil, and so `reference()` is never being called. I think this was supposed to be adding a reference to `res` anyways. 
looks like incorrect use of `\(varName)` was introduced here: https://github.com/migueldeicaza/SwiftGodot/commit/3f3bf924a533039454af43d3d25b284e0c096858

Fix exported resource references

---

.gitignore
Sources/SwiftGodotMacroLibrary/SceneTreeMacro.swift
Tests/SwiftGodotMacrosTests/SceneTreeMacroTests.swift

This PR works towards making @SceneTree closer to @BindNode by making the `path` argument optional.
Currently, `@SceneTree` requires an argument for the path:
```swift
class MyNode: Node2D {
@SceneTree(path: "SomePath/MyOtherNode")
var myOtherNode: Node2D?
}
```
There may be cases where providing a path is redundant or not desired, however.
This PR changes the macro to allow not providing a path argument. If the path argument is not provided in the macro, it will use the variable declarations identifier text instead of throwing an error.
Consider the following example:
```swift
class MyNode: Node2D {
@SceneTree var char2D: CharacterBody2D?
}
```
`@SceneTree` would look for a node named `char2D` exactly. This approach makes no assumptions on spacing or case; it is up to the user to ensure …

Make @SceneTree path argument optional

---

Generator/Generator/MethodGen.swift
Sources/SwiftGodot/EntryPoint.swift

Add call_object_method_bind_v
This variation calls one of object_method_bind_call_v or object_method_bind_ptrcall_v, which effectively inlines the
call to withArgPointers(). This should reduce code size since there's no need to generate an extra closure per call site.

call_object_method_bind_v

---

Generator/Generator/BuiltinGen.swift
Generator/Generator/ClassGen.swift
Generator/Generator/UtilityGen.swift
Sources/SwiftGodot/Native/LinearInterpolation.swift
Sources/SwiftGodot/Native/RotationConversion.swift
Sources/SwiftGodot/Native/Snapped.swift

This is the preliminary addition to replace some of the existing functions from Godot with native ones as well as filtering out some un-needed ones.
- Removes a lot of math functions like sin, cos, tan from being generated. These are unecessary because Swift already has those
- Removes lerp and inverse_lerp and implements a native version
- Removes snapped and implements a native version
- Removes angle calculations and implements a native one

Create Native Godot functions

---

Sources/SwiftGodotMacroLibrary/MacroGodot.swift
Tests/SwiftGodotMacrosTests/MacroGodotExportCategoryTests.swift
Tests/SwiftGodotMacrosTests/MacroGodotExportCollectionTests.swift

I noticed while working on #316 that for an array type, setting the `className: StringName("Array[Element]")` on the property is not enough for GDScript to be able to infer the type hinting.
For example when used as a param the auto complete showed the type as `Array` even though the className was `Array[int]`
I've also learned more about hint, and hintStr, so this PR updates the Export and Godot macros to take fuller advantage of the property info params.
I don't think `className: StringName("Array[Element]")` is actually needed anymore, but it doesn't seem to cause harm to. leave it either.
also usage is set to `.array` instead of `.default`

Export collection improvements

---

Sources/SwiftGodot/SwiftGodot.docc/Differences.md

I had a hard time figuring out why my Callable made with the macro was making the game freeze, turns out you have to call `<callable>.call()` method instead of just using `<callable>()`
I don't know if this behavior is a bug or not, but I think it might be worth it to include GDScript snippet to let the users know how to do this.

Add @Callable macro explainer in the documentation.

---

Package.swift
Sources/SwiftGodotTestability/GodotTestCase.swift
Tests/SwiftGodotEngineTests/Math/AABBTests.swift
Tests/SwiftGodotEngineTests/Math/BasisTests.swift
Tests/SwiftGodotEngineTests/Math/PlaneTests.swift
Tests/SwiftGodotEngineTests/Math/QuaternionTests.swift

These are just C++ tests from Godot's repository converted into Swift. It's a relatively cheap way for us to get some test coverage, and to make sure things work as the engine devs intended.

Add engine tests for AABB, Basis, Plane and Quaternion

---

Generator/Generator/BuiltinGen.swift
Tests/SwiftGodotEngineTests/Math/AABBTests.swift
Tests/SwiftGodotEngineTests/Math/BasisTests.swift
Tests/SwiftGodotEngineTests/Math/PlaneTests.swift
Tests/SwiftGodotEngineTests/Math/QuaternionTests.swift

There's already similar logic for general classes, but not for built-ins.

Omit first argument name in built-in struct methods when possible

---

Sources/SwiftGodotMacroLibrary/MacroCallable.swift
Sources/SwiftGodotMacroLibrary/MacroSharedApi.swift

Following the discussion on #327, I have implemented a check for async/throwing functions since currently it just does not compile and does not give an explanation on why.
This PR makes the code below throw an error before compile-time.
```swift
@Callable func test() async throws { // ERROR: @Callable does not support asynchronous or throwing functions
print("test")
}
```

Throw an error when async or throwing function have @Callable macro

---

Generator/Generator/BuiltinGen.swift

Fixes #345. No need to fix `Transform3D` because it only depends on `Basis` default init working correctly.

Fix default inits of Transform2D, Basis and Projection

---

Generator/Generator/BuiltinGen.swift
Sources/SwiftGodot/Core/GArray.swift

This will hook `GArray` to the generated indexing implementation already used in packed arrays.

Reuse collection conformance generation for GArray

---

Sources/SwiftGodot/MacroDefs.swift
Sources/SwiftGodotMacroLibrary/MacroGodot.swift
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift

Fixes #347. Classes can be annotated as `@Godot(.tool)` to make them run in editor akin to `@tool` scripts.

Prevent SwiftGodot subclasses from executing in editor by default

---

Sources/SwiftGodot/MacroDefs.swift
Sources/SwiftGodotMacroLibrary/MacroExportSubgroup.swift
Sources/SwiftGodotMacroLibrary/MacroGodot.swift
Tests/SwiftGodotMacrosTests/MacroGodotExportSubgroupTests.swift

resolves: #278 
```swift
@Godot class Car: Node {
#exportGroup("Vehicle")
#exportSubgroup("VIN")
@Export var vin: String = ""
#exportSubgroup("YMMS", prefix: "ymms_")
@Export var ymms_year: Int = 1998
@Export var ymms_make: String = "Honda"
@Export var ymms_model: String = "Odyssey"
@Export var ymms_series: String = "LX"
}
```

#278 add support for export subgroup

---

Sources/SwiftGodot/Core/Wrapped.swift
Sources/SwiftGodot/EntryPoint.swift
Sources/SwiftGodot/MacroDefs.swift
Sources/SwiftGodotMacroLibrary/InitSwiftExtensionMacro.swift
Tests/SwiftGodotMacrosTests/InitSwiftExtensionMacroTests.swift

Fixes #273. I don't see any problems with unregistering and reregistering classes using this solution. Class duplication discussed in the issue was probably due to `extensionInitCallbacks` accumulating hooks with each initialization, that should be fixed. If not, I'll look into it again when we have a more definitive fail case.

Fix hot reloading

---

Generator/Generator/BuiltinGen.swift

In GDScript `Color()` constructs a non-transparent black: `(0, 0, 0, 1)`

Make default Color init match GDScript

---

Sources/SwiftGodot/Extensions/Arithmetic.swift
Tests/SwiftGodotTests/BuiltIn/ColorTests.swift
Tests/SwiftGodotTests/BuiltIn/PlaneTests.swift
Tests/SwiftGodotTests/BuiltIn/QuaternionTests.swift
Tests/SwiftGodotTests/BuiltIn/Vector2Tests.swift
Tests/SwiftGodotTests/BuiltIn/Vector2iTests.swift
Tests/SwiftGodotTests/BuiltIn/Vector3Tests.swift
Tests/SwiftGodotTests/BuiltIn/Vector3iTests.swift
Tests/SwiftGodotTests/BuiltIn/Vector4Tests.swift
Tests/SwiftGodotTests/BuiltIn/Vector4iTests.swift

Follow-up to #359. Godot does not crash on arithmetic overflows, so neither should we.

Fix arithmetic overflow crash in unary minus operators

---

Sources/SwiftGodot/Core/StringExtensions.swift

Closes #344, closes #379. 
It's probably possible to make it match Swift string hashing:
```swift
extension String: Hashable {
/// Hashes the essential components of this value by feeding them into the
/// given hasher.
///
/// - Parameter hasher: The hasher to use when combining the components
///   of this instance.
public func hash(into hasher: inout Hasher) {
if _fastPath(self._guts.isNFCFastUTF8) {
self._guts.withFastUTF8 {
hasher.combine(bytes: UnsafeRawBufferPointer($0))
}
hasher.combine(0xFF as UInt8) // terminator
} else {
_gutsSlice._normalizedHash(into: &hasher)
}
}
}
```
by using `toUtf8Buffer`, but I don't think there's an effective way to get actual byte array from `PackedByteArray`.

Make StringName and GString Hashable

---

Sources/SwiftGodot/Variant.swift

I was getting this compile error
```
/Users/nvanfleet/src/PlantQuest/build/checkouts/SwiftGodot/Sources/SwiftGodot/Variant.swift:185:21: error: use of local variable 'ret' before its declaration
if let rc = ret as? RefCounted {
^
/Users/nvanfleet/src/PlantQuest/build/checkouts/SwiftGodot/Sources/SwiftGodot/Variant.swift:189:13: note: 'ret' declared here
let ret: T? = lookupObject(nativeHandle: value)
^
error: fatalError
```
Looks like the ret should be declared before it is used.
cc @migueldeicaza

Fix Variant ret

---

Sources/SwiftGodotMacroLibrary/MacroGodot.swift
Tests/SwiftGodotMacrosTests/MacroGodotExportCategoryTests.swift
Tests/SwiftGodotMacrosTests/MacroGodotExportCollectionTests.swift
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift

change `usage: .array` (back) to `usage: .default`

Exported `VariantCollection` and `ObjectCollection` types do not appear in the Editor

---

Generator/Generator/Data.swift
Generator/Generator/main.swift

Partly addresses #418. This makes source generation work, but there are still some issues with Windows build on Swift 5.10 remaining.

Fix extension api reading in Swift 5.10 on Windows

---

Plugins/CodeGeneratorPlugin/plugin.swift

Fixes #418 
We have two build commands here:
1. `prebuildCommand` which works as a source generator on Windows, but shouldn't work by design (on macOS it throws `a prebuild command cannot use executables built from source, including executable target 'Generator'`). On Swift 5.9 this command also added sources from `outputFilesDirectory` to the build, which does not happen on Swift 5.10. Not sure if we should report this, as our use case is wrong to begin with.
2. `buildCommand` which does not generate sources on Windows (the `.exe` never gets called), but works as a source provider through `outputFiles`. I have already reported the issue at https://github.com/apple/swift-package-manager/issues/6962
So combining the two broken things makes the build work again on Swift 5.10 toolchain. …

Fix build command execution on Windows using Swift 5.10

---

Sources/SwiftGodotTestability/GodotRuntime.swift
Sources/SwiftGodotTestability/GodotTestCase.swift
Tests/SwiftGodotEngineTests/Math/AStarTests.swift

Mainly the actor isolation one: 
`Main actor-isolated class 'GodotTestCase' has different actor isolation from nonisolated superclass 'XCTestCase'; this is an error in Swift 6`
Main actor isolation is not necessary for `GodotTestCase` since those test cases run inside `loadScene` callback, which happens on main thread.

Fix warnings in tests

---

Sources/SwiftGodot/Core/InspectableProperty.swift
Sources/SwiftGodot/Extensions/InputEvents.swift
Sources/SwiftGodot/Extensions/RefCountedExtensions.swift
Sources/SwiftGodot/Native/LinearInterpolation.swift
Sources/SwiftGodot/Native/RotationConversion.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/MainLevel-multiscript-2.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/MainLevel-multiscript-3.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/MainLevel-multiscript-4.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/MainLevel-multiscript-5.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/MainLevel-multiscript-6.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/MainLevel-multiscript-init.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/PlayerController-multiscript-2.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/PlayerController-starter-2.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/PlayerController-starter-3.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/PlayerController-starter-4.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/PlayerController-starter-5.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/PlayerController-starter-6.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/PlayerController-starter-7.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/PlayerController-starter-8.swift
Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/PlayerController-starter-init.swift

This leaves only 2 imports in `SwiftGodot` where `Foundation` is actually used:
- `PackedByteArray.asData()` returning `Data`
- `Numeric.snapped` native implementation using `floor()`
Both can be refactored without using `Foundation` dependency, which is too heavy for non-Darwin platforms compared to the convenience it brings. I think it should be up to users to decide whether they want to include `Foundation` into their game or not.

Clean up unnecessary Foundation imports

---

Package.swift

Macros tests don't work on Windows, as described in #317. This PR disables them for now.

Disable macros tests on Windows

---

Package.swift

Partly addresses #424, making it possible to use `SwiftGodotTestability` to test user extensions when extension itself depends on `SwiftGodotStatic`.

Add static version of SwiftGodot library

---

Generator/Generator/Printer.swift

Fixes #431 by using the `InputStream` workaround from #419

Fix consecutive builds on Windows using Swift 5.10

---

Sources/SwiftGodot/Native/Snapped.swift

Follow-up to #427. Deals with the last Foundation import.

Rewrite snapped without using Foundation

---

Sources/SwiftGodotMacroLibrary/MacroCallable.swift
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift

Prefix `Variant` in GodotCallable macro with `SwiftGodot` to prevent potential conflict with custom `Variant` type.

Prevent custom Variant type conflict (#450)

---

Sources/SwiftGodot/Core/Packed.swift
Sources/SwiftGodot/EntryPoint.swift

Zero-copy access to byte arrays across the gdextension interface is possible with `packed_byte_array_operator_index_const`, which compliments the version we already use in `withUnsafeMutableAccessToData` -- `packed_byte_array_operator_index`
```
// the new GDExtensionInterface method in this PR
let packed_byte_array_operator_index_const: GDExtensionInterfacePackedByteArrayOperatorIndexConst
```
It's useful with a Foundation-using helper method like
```
extension PackedByteArray {
/// Returns a Data pointing directly at the data in this PackedByteArray
public func asDataNoCopy() -> Data? {
withUnsafeConstAccessToData { ptr, count in 
Data(bytesNoCopy: .init(mutating: ptr), count: count, deallocator: .none)
}
}
}
```

Expose packed_byte_array_operator_index_const.

---

Generator/Generator/StringOperations.swift

I'm using a godot module that has an enum with `return`. It failed to build since `return` wasn't being escaped. This fixes that.

Add `return` to `escapeSwift`

---

Sources/SwiftGodot/MacroDefs.swift
Sources/SwiftGodotMacroLibrary/InitSwiftExtensionMacro.swift
Tests/SwiftGodotMacrosTests/InitSwiftExtensionMacroTests.swift

closes #464 
Allows registration of types to Godot at all `GDExtension.InitializationLevel` cases.
Originally, this was supposed to support exposing types only at `.editor` initialization level, but the solution was generalized to include all cases. Maybe some esoteric use cases might require exposing types at `.core` and `.servers` levels.
I was able to work out a way of keeping the original declaration intact, so no breaking changes were introduced to the macro API.
Also, I still have to add api documentation and make some little adjustments to the existing one. If the code's good to go already, I'll do it.

Extend `initSwiftExtension` macro to expose all initialization levels (#464)

---

Generator/Generator/DocModel.swift

Fixes #466. Non-greedy `.*?` should capture everything before the first `]`

Fix url handing regex

---

Sources/SwiftGodot/Core/Packed.swift
Sources/SwiftGodot/EntryPoint.swift

Building on #456 - the `subscript` `get` functions for `PackedXYZArray`s do not need writeable pointers from Godot.
This changeset, by using the `_const` versions of the packed array interface functions, can save memory allocations b/c the copy-on-write logic doesn't need to happen for read-only access.
(Some more performance work from my GodotVision profiling—hitting 90FPS is important there!)

Packed: _const interface for subscript getters

---

Sources/SwiftGodot/SwiftGodot.docc/WorkingInVsCode.md

The working in vscode instructions are missing this step to also set the minimum platform target to macOS 13.

Update WorkingInVsCode.md to include requirement for min platform target

---

Sources/SwiftGodot/Extensions/NodeExtensions.swift

Previously the node would be fetched from the tree each time it was referenced. Meaning this fetch would take place every frame if the property with the `@BindNode` (class property, used within function) was used in `_physicsProcess` or `_process`. The fetching now takes place the first time, and the cached result every time thereafter.

Result of getNode is now cached

---

Sources/SwiftGodot/Extensions/NodeExtensions.swift

Previously the `@BindNode` property wrapper would only fetch a node based on its property name. Leaving a mix of camel and pascal cased properties in the class. Basing the wrapper entirely on the property name also posed an issue if your node was nested within the tree. These changes allow one to use the property wrapper `@BindNode(withPath:)` to either specify a nested path, or to decouple the naming of the property and the node within Godot. As the initializer parameter is optional, this is a nonbreaking change.

Adds specifying a path to @BindNode

---

Generator/Generator/BuiltinGen.swift
Generator/Generator/ClassGen.swift
Generator/Generator/MethodGen.swift
Sources/SwiftGodot/Core/GArray.swift
Sources/SwiftGodot/Core/ObjectCollection.swift
Sources/SwiftGodot/Core/VariantCollection.swift

Third time is the charm!
Fixes #483 by adding `omittedFirstArgLabelList` and checking for any explicitly omitted labels in `BuiltinGen` and `MethodGen`. 
Also deprecated `GArray.append(value: Variant)` and updated internal usages.

Explicitly omit argument label for GArray.append

---

Sources/SwiftGodot/Core/Wrapped.swift

Originally, using ```Object.method_get_class``` meant that we tried using an object's dynamic type even if it was not registered with GDExtension, which resulted in falling back to the default case of using the static type from the method signature. This PR fixes this by introducing a call to ```gi.object_get_class_name```, which will return the name of the most specialized subtype that is still registered with GDExtension. If this fails for some reason, we fall back to the previous method.

Fix resolution of dynamic types when only proper supertypes are exposed through GDExtension

---

Sources/SwiftGodot/SwiftGodot.docc/WorkingInVsCode.md

a `launch` debug task can be created in vscode, which runs the godot game directly wiht `lldb` debugger.

doc: replace vscode debug method from `attach` to `launch`

---

Sources/SwiftGodotMacroLibrary/MacroGodot.swift
Tests/SwiftGodotMacrosTests/MacroGodotExportCategoryTests.swift
Tests/SwiftGodotMacrosTests/MacroGodotExportCollectionTests.swift
Tests/SwiftGodotMacrosTests/MacroGodotExportEnumTests.swift
Tests/SwiftGodotMacrosTests/MacroGodotExportSubgroupTests.swift
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift

In Swift 6, `_initializeClass` as a `static var` produces an error:
> Static property '_initializeClass' is not concurrency-safe because it is non-isolated global shared mutable state
There's no reason to for it to be a `var`, so make it a `let` instead.

use let instead of var for _initializeClass

---

Sources/SwiftGodotTestability/GodotRuntime.swift

The method `-[GodotApplicationDelegate applicationDidFinishLaunching:]` (which is part of Godot, not part of SwiftGodot) uses the environment variable `__CFBundleIdentifier` in a way that crashes if the variable is not set.
Terminal sets `__CFBundleIdentifier`, but Xcode does not.
This patch works around that crash.

work around Godot crash when __CFBundleIdentifier isn't set

---

Generator/Generator/ClassGen.swift
Sources/SwiftGodot/Core/Packed.swift
Sources/SwiftGodot/Core/Wrapped.swift
Sources/SwiftGodotMacroLibrary/PickerNameProviderMacro.swift
Tests/SwiftGodotTests/ObjectCollectionTests.swift
Tests/SwiftGodotTests/VariantCollectionTests.swift

This patch eliminates all the compiler warninsg I get under Xcode 16.0 beta 4:
PickerNameProviderMacro.swift:58:13
Initialization of immutable value 'types' was never used; consider replacing with assignment to '_' or removing it
RefCounted.swift:24:9
Result of call to 'initRef()' is unused
Array.swift:301:5
@discardableResult declared on a function returning Void is unnecessary
Packed.swift:13:13
'append(value:)' is deprecated: This method signature has been deprecated in favor of append(_:)
Wrapped.swift:143:28
Value 'node' was defined but never used; consider replacing with boolean test
Wrapped.swift:511:17
Result of call to 'retain()' is unused

eliminate warnings

---

Package.swift

Apple has been migrating its Swift repos to the swiftlang organization on Github. This patch updates the URLs in Package.swift to point at the new organization.

update dependencies to point at swiftlang repos

---

.gitignore
Generator/Generator/BuiltinGen.swift
Package.swift
Sources/SwiftGodot/Core/GArray.swift
Sources/SwiftGodot/Core/VariantCollection.swift
Sources/SwiftGodot/Core/VariantRepresentable.swift
Sources/SwiftGodot/Core/VariantStorable.swift
Sources/SwiftGodot/Variant.swift
Tests/SwiftGodotTests/MemoryLeakTests.swift

This patch addresses both leaks discussed in #513.
The changes in https://github.com/migueldeicaza/SwiftGodot/commit/d1d6ca47f0fc5bb16948017e1a6b2c6c8838b3b5 made several `Geometry2DTests` fail.
The actual unbalanced retain causing the leak in `VariantRepresentable.swift`:
```swift
extension ContentVariantRepresentable {
public init? (_ variant: Variant) {
guard Self.godotType == variant.gtype else { return nil }
var content = Self.zero
withUnsafeMutablePointer(to: &content) { ptr in
variant.toType(Self.godotType, dest: ptr) // <-- THIS IS THE UNBALANCED RETAIN
}
self.init(content: content)
}
}
```
The `variant.toType` function calls into Godot to copy out the built-in type stored in `variant`. If that built-in type has an internal reference count, Godot increments it. Then, the call to …

Add tests cases for, and fix, #513

---

Generator/Generator/ClassGen.swift
Sources/SwiftGodot/Core/ObjectCollection.swift
Sources/SwiftGodot/Core/VariantRepresentable.swift
Sources/SwiftGodot/Core/VariantStorable.swift
Sources/SwiftGodot/Core/Wrapped.swift
Sources/SwiftGodot/SwiftGodot.docc/Differences.md
Sources/SwiftGodot/SwiftGodot.docc/Exports.md
Sources/SwiftGodot/SwiftGodot.docc/Variants.md
Sources/SwiftGodot/Variant.swift

It doesn't seem like the GodotObject protocol has any reason to exist. This patch removes it.
-   The protocol has no requirements.
-   There is exactly one directly conforming type: Object. All
descendants of Object inherit the conformance, but any constraint
requiring GodotObject conformance can be rewritten to instead
require Object inheritance.
-   There are three functions with GodotObject constraints:
-   `VariantStorable.makeOrUnwrap`
-   `Variant.asObject`
-   `lookupObject`
All test cases pass if I change these constraints to require Object
inheritance instead of GodotObject conformance.

remove GodotObject protocol

---

Sources/SwiftGodot/Core/Wrapped.swift
Sources/SwiftGodot/EntryPoint.swift
Tests/SwiftGodotTests/WrappedTests.swift

I noticed this comment:
```
// TODO: what happens if the user subclasses but the name conflicts with the Godot type?
// say "class Sprite2D: Godot.Sprite2D"
```
The only way SwiftGodot can find out the type for some pointer passed from Godot is by checking the class name, we really can't allow class name conflicts: we could end up casting a pointer to the wrong type, leading to difficult-to-diagnose crashes. I think it's better to crash immediately if the extension tries to register a class name that's already been registered.

die if a class name has already been registered

---

Sources/SwiftGodotMacroLibrary/MacroCallable.swift

Fixes the warning I get with the @Callable macro:
` 'append(value:)' is deprecated: This method signature has been deprecated in favor of append(_:)`

Fix deprecation warning for @Callable

---

Tests/SwiftGodotMacrosTests/MacroGodotTests.swift

After `value` label was omitted in https://github.com/migueldeicaza/SwiftGodot/pull/488, the tests macro tests were still expecting the deprecated API. This PR fixes those tests failing.

Fix macro tests expecting deprecated `append` API

---

Generator/Generator/StringOperations.swift

While experimenting with customized extension APIs, I came across these identifiers that were not escaped previously.
Specifically, these 4 (`switch`, `public`, `private`, `for`) are used in <https://github.com/GodotSteam/GodotSteam>.

Add additional reserved words to generator

---

Generator/Generator/ClassGen.swift

Fixes #535
When using the inputEvent on CollisionObject3D, for example, the callback alway returns an InputEvent instance instead of the correct subclass. In the example code the if in mouse_input_event will never pass.
Example code:
```
class SomeNode: Node3D {
@SceneTree(path: "CollisionObject3D")
var nodeArea: CollisionObject3D?
public override func _ready() {
nodeArea?.inputEvent.connect(mouse_input_event)
}
func mouse_input_event(camera: Node, event: InputEvent, eventPosition: Vector3, normal: Vector3, _shape_idx: Int64) {
if event is InputEventMouse {
print("InputEventMouse") // Will never print
}
}
}
```
The original output would be 
```
let arg_1 = lookupLiveObject (handleAddress: ptr_1!) as? InputEvent ?? InputEvent (nativeHandle: ptr_1!)
```
Now it will be this if the type has a …

Fixed Generator issue when using class arguments not looking up subtypes

---

Sources/SwiftGodot/Variant.swift
Tests/SwiftGodotTests/MemoryLeakTests.swift

Fixes https://github.com/migueldeicaza/SwiftGodot/issues/544:
`variant_call` returns a retained copy, we don't need to `copy` it, but assume control over it instead.

Fix a 544 leak

---

Sources/SwiftGodot/Core/VariantStorable.swift
Sources/SwiftGodot/Variant.swift
Tests/SwiftGodotTests/MemoryLeakTests.swift

Fixes https://github.com/migueldeicaza/SwiftGodot/issues/541
Godot String (aka GString) is described as `"has_destructor": true`. In the case of the bug, it was created, Variant made a copy of it that it manages by itself, but it was never destructed. `GString` would manage its destruction in such a case. `GStringRaw` was removed as redundant.

Fix a 541 leak

---

.github/workflows/swift.yml

Now it should cancel runs for the older commits if newer commits are added in the PR.

Optimize GitHub actions configuration

---

Generator/Generator/BuiltinGen.swift
Generator/Generator/MethodGen.swift
Tests/SwiftGodotTests/MemoryLeakTests.swift

Some of the constructors were hard-coded and weren't updated in previous [marshaling PR](https://github.com/migueldeicaza/SwiftGodot/commit/8eebedd0b1ced5e8dcefd6a0c0a82c70bce878d7) with a similar scope.
Fixed leaks in variadic methods returning Godot `Variant` and `String`:
https://github.com/migueldeicaza/SwiftGodot/issues/552 in https://github.com/migueldeicaza/SwiftGodot/pull/550/commits/aa902c96808b25bd38ded3e8c55d32dc3747c49f 
https://github.com/migueldeicaza/SwiftGodot/issues/551 in https://github.com/migueldeicaza/SwiftGodot/pull/550/commits/1f4079d5b80c8a114742cfd7b32e2849deffe260 (we passed pointer to the `VariantContent`, where pointer to `GString.ContentType` content was expected.

Hardcoded constructors marshaling fix, some leaks fixes

---

Sources/SwiftGodotMacroLibrary/MacroGodot.swift

As per doc, Godot will expect a type name in `hintStr`, in our case it was en empty string that was treated as "TypedArray of type with empty name".
Now the methods are properly exported:
Fixes: https://github.com/migueldeicaza/SwiftGodot/issues/537

Don't add `.arrayType` hint when registering `@Callable` methods returning `GArray`

---

.gitignore

The vs-code Swift plugin has an experimental background indexing mode.
If it's enabled, it makes the index in `.index-build`.
This PR just adds that to the .gitignore.

Ignore auto-generated index.

---

.github/workflows/swift.yml
Sources/SwiftGodotTestability/GodotTestCase.swift
Sources/SwiftGodotTestability/GodotTestRunner.swift
Tests/SwiftGodotEngineTests/Math/AABBTests.swift

Currently, if the `swift build` or `swift test` commands fail, the GH action step will still be marked as succeeded.
This seems to be an artefact of the way we were re-running the tests from within the Godot engine; it resulted in the overall failure count being 0 even if there were actual failures.
This PR changes the way we run the tests, and should result in a non-zero exit status if a test does fail.
It also separates the XCTest run and the Swift testing run into two steps.
The default behaviour of `swift test` is to first run the XCTest engine, then run Swift testing engine. 
This results in the following confusing output at the end of the test run:
```
􀟈  Test run started.
􀄵  Testing Library Version: 102 (arm64e-apple-macos13.0)
􁁛  Test run with 0 tests passed after 0.001 seconds. …
```

Fail the GH build/test steps if the swift build/test actually failed.

---

Sources/SwiftGodotTestability/GodotTestCase.swift
Sources/SwiftGodotTestability/GodotTestRunner.swift
Tests/SwiftGodotTests/MemoryLeakTests.swift

This change does a few things:
- Uses a dummy test run class for tests when the Godot runtime isn't running.
- Adds some logging to clearly delineate the time when the tests are running in the engine
- Filters out non-engine tests when running in the engine (previously tests that just inherit from XCTestCase were running twice)
Using the dummy run class makes the test suites appear to contain no tests when they are run outside the engine:
```
Test Suite 'AABBTests' started at 2024-11-01 12:30:53.297.
Test Suite 'AABBTests' passed at 2024-11-01 12:30:53.297.
Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
```
Later when they run in the engine, the tests will show up:
```
Test Suite 'AABBTests' started at 2024-11-01 12:30:56.593.
Test Case …
```

Cleaner Test Output

---

Sources/SwiftGodot/Core/ClassServices.swift
Sources/SwiftGodot/Core/Wrapped.swift
Sources/SwiftGodot/EntryPoint.swift
Sources/SwiftGodot/Export.swift
Sources/SwiftGodot/Variant.swift
Sources/SwiftGodotTestability/GodotRuntime.swift

These changes refactor the extension interface into a single protocol that provides access to the library handle and the getProcAddr function, giving the implementation more flexibility in providing these to the bindings.

Refactor Extension Interface

---

Sources/SwiftGodot/Core/ClassServices.swift
Sources/SwiftGodot/Core/Wrapped.swift
Sources/SwiftGodot/EntryPoint.swift
Sources/SwiftGodot/Export.swift
Sources/SwiftGodot/Variant.swift
Sources/SwiftGodotTestability/GodotRuntime.swift

These changes refactor the extension interface into a single protocol that provides access to the library handle and the getProcAddr function, giving the implementation more flexibility in providing these to the bindings.

Refactor Extension Interface (with implementation-only GDExtension import)

---

.github/workflows/swift.yml
Generator/Generator/ClassGen.swift
Package.swift
Sources/SwiftGodot/Core/GenericSignal.swift
Sources/SwiftGodot/Core/SignalSupport.swift
Sources/SwiftGodot/Variant.swift
Tests/SwiftGodotTests/MarshalTests.swift
Tests/SwiftGodotTests/MemoryLeakTests.swift
Tests/SwiftGodotTests/SignalTests.swift
Tests/SwiftGodotTests/VariantTests.swift

See also #42 
Instead of generating a helper class for each signal property, we use a single GenericSignal which can be specialised with the list of argument types that the signal contains.

GenericSignal helper class

---

Generator/Generator/ClassGen.swift

Since we already omit cosh and tanh.

don't generate sinh

---

Sources/SwiftGodot/EntryPoint.swift

While "scene" level is going to be the right choice for the majority of projects, .editor might be a more appropriate choice for an Extension which is purely an in-editor tool. Likewise, an Extension that has to add Core or Server types might need the earlier settings. So, make this a parameter on initializeSwiftModule() with a default value of .scene.

Parameterize the "minimum_initialization_level" for the extension

---

Sources/SwiftGodot/EntryPoint.swift

Fixes a broken cast from `GDExtension.InitializationLevel` to `GDExtensionInitializationLevel`.

Fix Entrypoint

---

Sources/SwiftGodotTestability/EmbeddedXCTest/EmbeddedTestCase.swift
Sources/SwiftGodotTestability/EmbeddedXCTest/EmbeddingController.swift

We were incorrectly re-running all test suites inside the Godot engine. This causes a (non-fatal) exception for suites that just inherit from `XCTestCase`, warning that it had already been run once.
This change only register suites that contain EmbeddedTestCase tests for re-running inside the engine.

Only run non-embedded tests once.

---

Sources/SwiftGodot/Core/ClassServices.swift
Sources/SwiftGodotMacroLibrary/MacroGodot.swift
Sources/SwiftGodotMacroLibrary/MacroSharedApi.swift
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift
Tests/SwiftGodotTests/MarshalTests.swift

Fix for PropInfo incorrectly constructed in macro processor for return values and parameters in callable, when it was a Variant/Variant?.
Fixes https://github.com/migueldeicaza/SwiftGodot/issues/625

Fix @Callable containing Variants as parameters and return types

---

.github/workflows/swift.yml
Package.swift
Plugins/CodeGeneratorPlugin/plugin.swift
Plugins/EntryPointGeneratorPlugin/EntryPointGeneratorPlugin.swift
Sources/SwiftGodotMacroLibrary/MacroCallable.swift
Tests/SwiftGodotMacrosTests/MacroGodotTestCase.swift
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift

~~This is an experiment.~~
This changes swift-tools-version to 6.0, but then opts out all of the non-plugin targets from the Swift 6.0 language mode (for now).
There is no way to opt out for plugins, so they are updated (the updates are fairly trivial).
Partly I did this to see whether forcing the tools version to 6.0 helped with any of the Windows build problems.
It does also have the advantage that we can migrate targets to Swift 6.0 one at a time, when the time comes.
Obviously this change would force a dependency on the Swift 6.x toolchain. That may be a good thing, if it reduces the need to cope with legacy compiler weirdness (eg windows compiler features lagging behind).

Adopt Swift 6.0 Tools Version

---

.github/workflows/swift.yml
Package.swift
Plugins/CodeGeneratorPlugin/plugin.swift

Contains the following changes:
- brings Windows into line with the other platforms by building SwiftGodot as a shared library
- updates the Xcode/Swift versions in the CI workflow
- removes a workaround for the Generator plugin on Windows, which no longer seems to be necessary when building with Swift 6.1.

Build As DLL, Use Swift 6.1 prelease, on Windows

---

.github/workflows/swift.yml

Github have updated their Xcode versions, and no longer have 16.0, so we need to update to 16.2.
At the same time, upgrading the Windows CI to a pre-release of 16.1 potentially fixes some problems with the generator plugin.

Fix Xcode version for CI

---

Sources/SwiftGodot/Core/Packed.swift
Tests/SwiftGodotTests/BuiltIn/PackedArrayTests.swift

Noticed that there weren't any straightforward ways to construct PackedVector\*Arrays from arrays of Vector\*, so I hacked this together. It appears to work and passes tests. Thank you for the awesome project!
**Covered:**
- PackedColorArray
- PackedVector2Array
- PackedVector3Array
- PackedVector4Array
**Not Covered:**
- PackedStringArray

Extend convenience initializer coverage for Packed*Array

---

.github/workflows/swift.yml
Sources/SwiftGodot/Core/SignalRegistration.swift
Sources/SwiftGodot/MacroDefs.swift

If we're happy with the new `@Signal` macro, we should probably aim to strip the old one out eventually.
A first step is to deprecate the old one, and the associated API.

Deprecate old signal API

---

Generator/Generator/Enums.swift
Sources/SwiftGodot/Core/Arguments.swift
Sources/SwiftGodot/Core/VariantCollection.swift
Tests/SwiftGodotTests/VariantTests.swift

See [this conversation](https://swiftongodot.slack.com/archives/C05BYJ95S5D/p1737984087090499).
We're generating a debugDescription for enums, but it's not really required.
Removing it will lower the exported symbol count, which is a GoodThing™

Remove Generated Enum debugDescription

---

Sources/EntryPointGenerator/EntryPointGenerator.swift
Sources/EntryPointGenerator/GodotMacroSearchingVisitor.swift

The entrypoint generator spams the log with information that's not strictly necessary.
This PR changes the tool so that the default output is simply one line, of the form: `Generated swift_entry_point, registering <n> classes, in EntryPoint.generated.swift.`.
The previous logging is still available when invoking the tool manually, by passing a `--verbose` flag.

Reduce Entrypoint Generator Output

---

Generator/Generator/BuiltinGen.swift
Sources/SwiftGodotMacroLibrary/MacroCallable.swift
Sources/SwiftGodotMacroLibrary/MacroExport.swift
Sources/SwiftGodotMacroLibrary/MacroGodot.swift
Sources/SwiftGodotMacroLibrary/MacroSharedApi.swift
Tests/SwiftGodotMacrosTests/MacroGodotExportCategoryTests.swift
Tests/SwiftGodotMacrosTests/MacroGodotExportCollectionTests.swift
Tests/SwiftGodotMacrosTests/MacroGodotExportEnumTests.swift
Tests/SwiftGodotMacrosTests/MacroGodotExportSubgroupTests.swift
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift
Tests/SwiftGodotMacrosTests/SceneTreeMacroTests.swift

This is a fix for  #667
- Updated GodotCallable and GodotExport macros to emit fully qualified SwiftGodot.Variant instead of just Variant to prevent clashes with user-defined Variant type.
- Changed getTypeName() in shared API to return fully qualified `SwiftGodot.Variant` for both optional and non-optional types.
- Added helper function splitParameterQualifiers(FunctionParameterSyntax) that returns a tuple (member_name?, type_name, is_optional).
This PR is missing:
- ~tests~ (**EDIT**: Added.)
- fix for clash of custom ObjectID (**EDIT**: Can be worked around. Not needed for this PR)

Prevent conflict with user-defined Variant. Fix for #667

---

Sources/SwiftGodot/MacroDefs.swift
Sources/SwiftGodotMacroLibrary/MacroGodot.swift
Sources/SwiftGodotMacroLibrary/MacroSharedApi.swift
Sources/SwiftGodotMacroLibrary/SwiftSyntaxExtensions.swift
Tests/SwiftGodotMacrosTests/MacroGodotBuildTest.swift
Tests/SwiftGodotMacrosTests/MacroGodotTestCase.swift
Tests/SwiftGodotMacrosTests/MacroGodotTests.swift
Tests/SwiftGodotMacrosTests/Resources/MacroGodotTests.testCallableAutoSnakeCase.swift

Add `autoSnakeCase` parameter to `@Callable`. It will allow customising how function name is exported to Godot.
Swift common convention is `camelCase` while Godot uses `snake_case` for functions.
Default value is `false`. In the future I expect to make it depend on SPM trait, so that default value is `true` for new projects, and `false` for projects that opt-in the legacy behavior.
That behavior will align with `@Export` macro, which I believe is the most convenient one.

Add `autoSnakeCase` to @Callable

---

Sources/SwiftGodot/Core/Arguments.swift
Tests/SwiftGodotMacrosTests/MacroGodotBuildTest.swift
Tests/SwiftGodotTests/MarshalTests.swift

Fix cases like
```
@Callable
func nodeAddedToScene(node: Node?)
```
Resolved by making a `T?` overload a disfavoured one.

Fix optional object argument unwrapping ambiguity

---

Generator/Generator/ClassGen.swift
Generator/Generator/MethodGen.swift
Generator/Generator/main.swift
Sources/ManualExtension/ManualExtension.swift
Sources/SwiftGodot/Core/SignalProxy.swift
Sources/SwiftGodot/Core/Wrapped.swift
Sources/SwiftGodot/FastVariant.swift
Sources/SwiftGodot/Variant.swift
Tests/SwiftGodotEngineTests/Math/AStarTests.swift
Tests/SwiftGodotMacrosTests/MacroGodotBuildTest.swift

There is only one `required init` chain now, that takes `InitContext`. In case users _do_ need a custom `init` they will have only:
```
required init(_ context: InitContext) {
super.init(context)
addPoint (id: Self.A, position: Vector3 (x: 0, y: 0, z: 0))
addPoint (id: Self.B, position: Vector3 (x: 1, y: 0, z: 0))
addPoint (id: Self.C, position: Vector3 (x: 0, y: 1, z: 0))
addPoint (id: Self.X, position: Vector3 (x: 0, y: 0, z: 1))
connectPoints (id: Self.A, toId: Self.B)
connectPoints (id: Self.A, toId: Self.C)
connectPoints (id: Self.B, toId: Self.C)
connectPoints (id: Self.X, toId: Self.A)
}
```
They can't construct their own, it's required for `super.init`, so it's almost impossible to get wrong.
At the same time default initialiser `init()` is accessible for all `Object`-derived …

Implement single init chain

---

Sources/SwiftGodot/Core/Packed.swift

Adds ExpressibleByArrayLiteral conformance to all PackedXArray types. Allows you to do this:
```swift
let vertices : PackedVector3Array = [
Vector3(x: -0.5, y: 0, z: -0.5),
Vector3(x: -0.5, y: 0, z:  0.5),
Vector3(x:  0.5, y: 0, z: -0.5),
Vector3(x:  0.5, y: 0, z:  0.5)
]
```
Implementation just passes the elements directly to the `init(_ values)` initializer.

Add ExpressibleByArrayLiteral to packed array types

---

Sources/SwiftGodot/SwiftGodot.docc/SwiftGodot Tutorials.tutorial

DocC automatically adds "Tutorials" to the end of the provided `@Tutorials` page title.
Right now it is rendered this way:
By removing the "Tutorials" at the end of the given name, the final rendered title is "SwiftGodot Tutorials".
This should not change the URL addresses of the tutorial pages.

Remove duplicated "Tutorials" in tutorials page title
