migueldeicaza/SwiftGodot

- scripts/make-swiftgodot-framework
- scripts/release
> Add Apple Silicion support in XCFramework

- .github/workflows/swift.yml
Thank you for this great project!
I've made a small change to fix the CI.
You can view the successful run in my fork [here](https://github.com/wacumov/SwiftGodot/actions/runs/5782926693).
> Use Xcode 14.3 to fix CI

- Sources/SwiftGodot/Core/Wrapped.swift
> Fix superclass reflection

- Sources/SwiftGodot/EntryPoint.swift
> Fix vector3 index operator

- Tests/SwiftGodotMacrosTests/MacroGodotTests.swift
> Update inits in macro tests

- Sources/SwiftGodot/Extensions/Arithmetic.swift
> Add missing scaling operators for vectors

- README.md
Update #initSwiftExtension example
> Update initSwiftExtension example in README.md

- Sources/SwiftGodotMacroLibrary/MacroExport.swift
- Tests/SwiftGodotMacrosTests/MacroGodotTests.swift
Fixes #208. This should make CI checks work again.
> Fix export macro for optional builtins

- Package.swift
- Sources/SwiftGodot/MacroDefs.swift
Proposed change for #214
Needs to be tested on windows
> Update MacroDefs.swift for windows compat 

- Generator/Generator/ClassGen.swift
- Generator/Generator/MethodGen.swift
- Sources/SwiftGodot/Core/ObjectCollection.swift
- Sources/SwiftGodot/Core/Wrapped.swift
> Fix crash when setting incorrect type in editor

- Sources/SwiftGodot/Variant.swift
- Tests/SwiftGodotTests/VariantTests.swift
> Fix generic parameters of mutable pointers in Variant init

- Sources/SwiftGodotMacroLibrary/MacroExport.swift
> Add reference count handling for Export macro

- Sources/SwiftGodot/Core/Wrapped.swift
> Fix memory leak of framework wrappers

- Makefile
- Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/Package-starter-4.swift
- Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/SimpleRunnerDriver-starter-3.txt
- Sources/SwiftGodot/SwiftGodot.docc/Tutorials/Your First Extension.tutorial
fixes for the steps that stopped me when doing the tutorial for the first time
> docs improvements

- Sources/SwiftGodotTestability/GodotRuntime.swift
- Sources/SwiftGodotTestability/GodotTestCase.swift
- Tests/SwiftGodotTests/WrappedTests.swift
Started this as a part of #231, but haven't had a chance to finish it until now.
Commenting out either 
https://github.com/migueldeicaza/SwiftGodot/blob/831e1fefcfaf461554fc5441cfb19df08e485af0/Sources/SwiftGodot/Core/Wrapped.swift#L360
or
https://github.com/migueldeicaza/SwiftGodot/blob/831e1fefcfaf461554fc5441cfb19df08e485af0/Sources/SwiftGodot/Core/Wrapped.swift#L310
triggers the test, so I think it works.
> Add memory leak tests

- Sources/SwiftGodot/Core/SignalSupport.swift
1. Declare .proxy as optional, so it can be nil'd to break cycles after a signal is disconnected.
2. Add explicit calls to .free() when the SignalProxy is no longer needed.
3. When one-shot signals are used, free the proxy after callback is called.
> Fix leaks when managing signals

- .gitignore
- Makefile
Close https://github.com/migueldeicaza/SwiftGodotDocs/issues/2
> Add source service support

- Sources/SwiftGodotMacroLibrary/MacroGodot.swift
- Tests/SwiftGodotMacrosTests/MacroGodotExportCategoryTests.swift
- Tests/SwiftGodotMacrosTests/MacroGodotExportCollectionTests.swift
This should resolve #298
@migueldeicaza
> 298 exported properties not appearing in editor

- .github/workflows/swift.yml
- Generator/Generator/MethodGen.swift
A hacky workaround for #299 
Im sure there is probably a more correct way to fix this, but this works for now :>
Also adds a new github action to check windows builds
> Patch to fix windows builds

- Sources/SimpleExtension/Demo.swift
- Sources/SwiftGodot/Native/LinearInterpolation.swift
- Tests/SwiftGodotTests/LinearInterpolationTests.swift
- Tests/SwiftGodotTests/SnappingTests.swift
Long story short my original linear interpolation was bugged. I had tested things but then made a few mistakes trying to arrange how the extension worked and caused an issue. So here is the fix with a cleanup as well as tests for snapping and linear interpolation.
> Fix Linear Interpolation

- Sources/SwiftGodot/Core/ObjectCollection.swift
- Sources/SwiftGodot/Core/VariantCollection.swift
- Sources/SwiftGodotMacroLibrary/Extensions/SwiftSyntax+MacroExport.swift
- Sources/SwiftGodotMacroLibrary/Extensions/VariableDeclSyntax+MacroExport.swift
- Sources/SwiftGodotMacroLibrary/MacroCallable.swift
- Sources/SwiftGodotMacroLibrary/MacroGodot.swift
- Sources/SwiftGodotMacroLibrary/MacroSharedApi.swift
- Tests/SwiftGodotMacrosTests/MacroGodotTests.swift
Resolves:
- #310
- #313
- #314
- #315
branched off of #311
> Callable array return type

- Generator/Generator/Arguments.swift
> Fix StringName argument generation

- Generator/Generator/BuiltinGen.swift
> Fix static method generation in built-in structs

- Generator/Generator/BuiltinGen.swift
> Fix Quaternion default init

- Sources/SwiftGodot/Extensions/PhysicsDirectSpaceState3D+IntersectRayResult.swift
- Tests/SwiftGodotTests/IntersectRayResultTests.swift
> adds PhysicsDirectSpaceState3D.IntersectRayResult and tests

- Sources/SwiftGodot/SwiftGodot.docc/WorkingInVsCode.md
Documentation for using Visual Studio Code to develop SwiftGodot on Windows, Linux, or Mac
> Document VS Code

- Generator/Generator/Enums.swift
- Generator/Generator/MethodGen.swift
- Sources/SwiftGodot/EntryPoint.swift
- Sources/SwiftGodot/Variant.swift
> Specify Int size for generated enums

- Sources/SwiftGodotMacroLibrary/MacroExport.swift
- Tests/SwiftGodotMacrosTests/MacroGodotExportCategoryTests.swift
- Tests/SwiftGodotMacrosTests/MacroGodotTests.swift
> Fix editor crash when trying to set mismatched value to exported property

- Sources/SwiftGodotMacroLibrary/MacroGodot.swift
- Tests/SwiftGodotMacrosTests/MacroGodotExportCategoryTests.swift
> fixes isse #353

- Generator/Generator/BuiltinGen.swift
- Sources/SwiftGodot/EntryPoint.swift
Closes #46. Sort of closes #45, it was already done, this PR just generalizes keyed access a bit.
> Add indexing support

- Sources/SwiftGodot/Native/Snapped.swift
- Tests/SwiftGodotTests/SnappingTests.swift
> Fix snapping implementation

- Sources/SwiftGodot/Extensions/Arithmetic.swift
> Add unary minus operators

- Sources/SwiftGodot/Core/Wrapped.swift
Can we please get rid of these? They are flooding my console output with information that I dont care about.
Relates to #330
> Remove annoying prints

- Sources/SwiftGodot/Core/Wrapped.swift
- Sources/SwiftGodotMacroLibrary/MacroExport.swift
- Tests/SwiftGodotMacrosTests/MacroGodotExportCategoryTests.swift
- Tests/SwiftGodotMacrosTests/MacroGodotTests.swift
> Fix conflicting variable name in export macro

- Tests/SwiftGodotMacrosTests/MacroGodotExportSubgroupTests.swift
Fix CI checks after a little desync in PRs
> Update export subgroup tests

- Tests/SwiftGodotTests/BuiltIn/ColorTests.swift
> Fix test compilation

- Sources/SwiftGodot/Core/SignalSupport.swift
> Make async interface of signals connect on main thread

- Sources/SwiftGodot/Core/Wrapped.swift
- Sources/SwiftGodotTestability/GodotTestCase.swift
> Add object cleaning after each test

- Sources/SwiftGodot/EntryPoint.swift
- Sources/SwiftGodot/Variant.swift
`variant_get_type_name` was missing in eca0c70bfa3fe1be95190299e7c0c2ce4a166842
> Fix package compilation

- Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/PlayerController-multiscript-2.swift
- Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/PlayerController-starter-6.swift
- Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/PlayerController-starter-7.swift
- Sources/SwiftGodot/SwiftGodot.docc/Resources/Tutorials/Sources/PlayerController-starter-8.swift
`limitLength(length:)` is outdated after c44bc91e3755d4af391d7a4ea62606a0deb45aed
> Fix tutorials compilation

- README.md
Updates the README with the following changes:
- Adds metadata badges for Swift version, SPM support, license and more.
- Adds section with info about contributing
- Adds section detailing the platforms supported by the project
- Adds section summarizing the current development status.
> Add additional platform and project info to readme

- README.md
Added a link to a bigger example I'm working on. 
I'm transforming [this godot c# tutorial](https://www.udemy.com/course/create-a-complete-grid-based-puzzle-game-godot-4-c-sharp) to swift. 
Currently is a work in progress, I don't have a lot of time, and also swift is not my main language, it will take a lot of time for me to complete (If I ever have time to complete it). 
I hope it can be helpfull.
> Added an extra example in the  tutorials and documentstions

- Sources/SwiftGodot/Core/ClassServices.swift
- Sources/SwiftGodot/Core/Wrapped.swift
- Tests/SwiftGodotTests/SignalTests.swift
- Tests/SwiftGodotTests/ValidatePropertyTests.swift
> Surface _validate_property method in Godot for allowing custom properties to be controlled

- README.md
https://github.com/elijah-semyonov/SwiftGodotTemplate
> Add `SwiftGodotTemplate` link to README

- Generator/Generator/MethodGen.swift
From Gabor Koncz: Previously assert(method.isVirtual) (along with its assert (!method.isVirtual) pair) expressed the precondition that a method is virtual if and only if it has a method hash. However, as previously discussed here, there were changes in the API generation which resulted in all methods having a method hash, which made the precondition no longer apply. This meant that to separate the two cases, we no longer check the existence of a method hash, but we directly check the isVirtual boolean, and so the assertions there would be redundant.
There have been some changes to the api generation in 4.4; one of these is that all methods (including virtual ones) have a hashcode now, so we cannot use that information to determine virtual-ness in the SwiftGodot proxy generation. These …
> Preparation for 4.4 API update.

- Sources/SwiftGodot/SwiftGodot.docc/Variants.md
> Fix typos in docs
